sudo: false
dist: xenial
language: python
cache: pip
git:
  lfs_skip_smudge: true
matrix:
  include:
  - python: '3.7'
    os: linux
before_install:
- git config lfs.fetchexclude "pymontecarlo_penepma/penepma"
- git lfs pull
install:
- ls -la pymontecarlo/pymontecarlo-penepma/pymontecarlo_penepma/penepma/bin_linux
- pip install --upgrade git+https://github.com/pymontecarlo/pymontecarlo.git@async
- pip install --cache-dir $HOME/.pip-cache --upgrade git+https://github.com/pymontecarlo/pypenelopetools.git
- pip install --upgrade pip codecov
- pip install --upgrade -e .[develop,gui]
script:
- pytest
after_success:
- codecov
notifications:
  email: false
